export default {
    "Sala / Sala de jantar": {
        "Aparador": 0.33,
        "Banqueta - Puff": 0.11,
        "Bar grande": 1.1,
        "Bar pequeno": 0.66,
        "Baú": 0.44,
        "Buffet": 1.1,
        "Cadeira com braços": 0.33,
        "Cadeira simples": 0.22,
        "Console de parede": 0.33,
        "Cristaleira": 0.88,
        "Escrivaninha grande": 1.1,
        "Escrivaninha pequena": 0.66,
        "Estante alta": 0.66,
        "Estante baixa": 0.33,
        "Mesa de centro": 0.33,
        "Mesa console": 0.33,
        "Mesa de jantar": 0.88,
        "Piano armário": 6.6,
        "Piano de cauda": 6.6,
        "Poltrona simples": 0.55,
        "Quadros": 0.11,
        "Rack": 0.33,
        "Sofá 2 lugares": 1.1,
        "Sofá 3 lugares": 1.65,
        "Sofá 4 lugares": 2.2,
        "Som/Vídeo": 0.33,
        "TV": 0.33,
    },
    "Quarto / Suíte": {
        "Arca": 0.44,
        "Armário 2 portas desmontado": 1.1,
        "Armário 3 portas desmontado": 1.65,
        "Berço com colchão": 0.33,
        "Cabideiro": 0.33,
        "Cama beliche com colchão": 2.2,
        "Cama casal com colchão": 1.43,
        "Cama de solteiro com colchão": 1.1,
        "Cômoda": 0.44,
        "Mesa de cabeceira": 0.22,
        "Penteadeira": 0.77,
        "Quadros": 0.11,
    },
    "Cozinha": {
        "Armário paneleiro": 1.1,
        "Armário de parede pequeno com 2 portas": 0.22,
        "Cadeira": 0.66,
        "Exaustor": 0.11,
        "Freezer": 0.88,
        "Fogão (4 bocas}": 0.33,
        "Fogão (6 bocas}": 0.55,
        "Forninho": 0.11,
        "Geladeira": 0.99,
        "Máquina de lavar louça": 0.55,
        "Máquina de lavar/secar": 0.55,
        "Mesa de cozinha": 0.33,
        "Micro-ondas": 0.11,
    },
    "Home Office": {
        "Armário (alto de 2 portas}": 1.1,
        "Arquivo": 0.55,
        "Balcão": 0.55,
        "Cadeira": 0.22,
        "Cofre": 0.55,
        "Escrivaninha": 0.44,
        "Estante de aço": 1.1,
        "Fax": 0.11,
        "Impressora/Xerox": 0.33,
        "Mesa": 0.55,
        "Microcomputador": 0.33,
        "Poltrona": 0.55,
    },
    "Diversos": {
        "Ar condicionado": 0.33,
        "Aquecedor": 0.22,
        "Arquivo": 0.56,
        "Bancada": 0.33,
        "Bicicleta": 0.33,
        "Caixa": 0.22,
        "Caixa para cristais": 0.11,
        "Caixa plástica": 0.22,
        "Máquina de costura": 0.44,
    },
}
