export default [
    {
        title: "Eu preciso de um box no tamanho:",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        question: [],
        tamanhos: ["PP", "P", "M", "G", "S"],
        itens: [],
    },
    {
        title: "Para onde enviaremos o orçamento instantâneo:",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: ["nome", "sobreNome", "telefone", "email"],
        question: [],
        tamanhos: [],
        itens: [],
    },
    {
        title: "Eu preciso guardar por:",
        subtitle: "Tempo aproximado, não precisa ser exato",
        final: false,
        isBudget: false,
        btn: [],
        month: [
            "1_a_3",
            "4_a_6",
            "7_a_12",
            "indefinido",
        ],
        form: [],
        question: [],
        tamanhos: [],
        itens: [],
    },
    {
        title: "O seu orçamento ficará entre:",
        subtitle: "",
        final: false,
        isBudget: true,
        btn: [],
        month: [],
        form: [],
        question: [],
        tamanhos: [],
        itens: [],
    },
    // {
    //     title: "Eu vou guardar objetos:",
    //     subtitle: "",
    //     final: false,
    //     isBudget: false,
    //     btn: [ 
    //         "empresa",
    //         "casa",
    //         "ambos",            
    //     ],
    //     month: [],
    //     form: [],
    //     question: [],
    //     tamanhos: [],
    //     itens: [],
    // },
    {
        title: "Eu vou guardar itens da Sala?",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [6, 1],
        itens: [],
    },
    {
        title: "Sala / Sala de jantar 1 de 5",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "APARADOR",
            "BANQUETA-PUFF",
            "BAR-GRANDE",
            "BAR-PEQUENO",
            "BAU",
            "BUFFET",
        ],
    },
    {
        title: "Sala / Sala de jantar 2 de 5",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "CADEIRA-COM-BRACOS",
            "CADEIRA-SIMPLES",
            "CONSOLE-DE-PAREDE",
            "CRISTALEIRA",
            "ESCRIVANINHA-GRANDE",
            "ESCRIVANINHA-PEQUENA",
        ]
    },
    {
        title: "Sala / Sala de jantar 3 de 5",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ESTANTE-ALTA",
            "ESTANTE-BAIXA",
            "MESA-DE-CENTRO",
            "MESA-CONSOLE",
            "MESA-DE-JANTAR",
            "PIANO",
        ]
    },
    {
        title: "Sala / Sala de jantar 4 de 5",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "PIANO-DE-CAUDA",
            "POLTRONA-SIMPLES",
            "QUADROS",
            "RACK",
            "SOFA-2-LUGARES",
            "SOFA-3-LUGARES",
        ]
    },
    {
        title: "Sala / Sala de jantar 5 de 5",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "SOFA-4-LUGARES",
            "SOM",
            "TV",
        ]
    },
    {
        title: "Eu vou guardar itens do quarto?",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [3, 1],
        itens: [],

    },
    {
        title: "QUARTO / SUÍTE 1 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ARCA",
            "ARMARIO-2-PORTAS",
            "ARMARIO-3-PORTAS",
            "BERCO-COM-COLCHAO",
            "CABIDEIRO",
            "BELICHE",
        ]
    },
    {
        title: "QUARTO / SUÍTE 2 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "CAMA-CASAL",
            "CAMA-SOLTEIRO",
            "COMODA",
            "MESA-DE-CABECEIRA",
            "PENTEADEIRA",
            "QUADROS",
        ]
    },
    {
        title: "Eu vou guardar itens da cozinha?",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [4, 1],
        itens: [],
    },
    {
        title: "Cozinha 1 de 3",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ARMARIO-PANELEIRO",
            "ARMARIO-DE-PAREDE-2-PORTAS",
            "CADEIRA",
            "EXAUSTOR",
            "FREEZER",
            "FOGAO-4-BOCAS",
        ]
    },
    {
        title: "Cozinha 2 de 3",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "FOGAO-6-BOCAS",
            "FORNINHO",
            "GELADEIRA",
            "MAQUINA-LAVA-LOUCA",
            "MAQUINA-DE-LAVAR-SECAR",
            "MESA-DE-COZINHA",
        ]
    },
    {
        title: "Cozinha 3 de 3",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "MICROONDAS",
        ]
    },
    {
        title: "Eu vou guardar itens diversos?",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [3, 1],
        itens: [],
    },
    {
        title: "DIVERSOS 1 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ARCONDICIONADO",
            "AQUECEDOR",
            "ARQUIVO",
            "BANCADA",
            "BICICLETA",
            "CAIXA",
        ]
    },
    {
        title: "DIVERSOS 2 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "CAIXA-PARA-CRISTAIS",
            "CAIXA-PLASTICA",
            "MAQUINA-DE-COSTURA",
        ]
    },
    {
        title: "Eu vou guardar itens do home office?",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [3, 1],
        itens: [],
    },
    {
        title: "Home Office 1 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ARMARIO-2-PORTAS",
            "ARQUIVO",
            "BALCAO",
            "CADEIRA",
            "COFRE",
            "ESCRIVANINHA",
        ]
    },
    {
        title: "Home Office 2 de 2",
        subtitle: "",
        final: false,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [
            "ESTANTE-DE-ACO",
            "FAX",
            "IMPRESSORA",
            "MESA",
            "MICROCOMPUTADOR",
            "POLTRONA",
        ]
    },
    {
        title: "",
        subtitle: "",
        final: true,
        isBudget: false,
        btn: [],
        month: [],
        form: [],
        tamanhos: [],
        question: [],
        itens: [],
    },
]

